import React, { useEffect, useState } from 'react';
import { Loader2, Save, ShieldCheck } from 'lucide-react';
import { getContactPreferences, saveContactPreferences, type ContactPreferences, type ContactPreferenceStatus } from '../../lib/privacy';

const labels: Record<ContactPreferenceStatus, string> = { NOT_INFORMED: 'Não informado', ALLOWED: 'Autorizado', REFUSED: 'Não autoriza' };

export function ContactPreferencesPanel({ patientId, canManage }: { patientId: string; canManage: boolean }) {
  const [value, setValue] = useState<ContactPreferences | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  useEffect(() => { const controller = new AbortController(); void getContactPreferences(patientId, controller.signal).then(setValue).catch(() => setMessage('Não foi possível consultar as preferências de contato.')); return () => controller.abort(); }, [patientId]);
  const update = (field: 'whatsapp' | 'phone' | 'email', status: ContactPreferenceStatus) => setValue((current) => current ? { ...current, [field]: status } : current);
  const save = async () => { if (!value || !canManage) return; setSaving(true); setMessage(''); try { setValue(await saveContactPreferences(patientId, { whatsapp: value.whatsapp, phone: value.phone, email: value.email, source: value.source || 'REGISTRO_DA_CLINICA' })); setMessage('Preferências de contato salvas.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível salvar as preferências.'); } finally { setSaving(false); } };
  return <section aria-labelledby="contact-preferences-title" className="mt-5 rounded-2xl border border-bhon-border bg-bhon-ivory/40 p-4 sm:p-5"><div className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-bhon-teal/15 text-bhon-teal"><ShieldCheck className="h-5 w-5" aria-hidden="true" /></span><div><h2 id="contact-preferences-title" className="font-display text-base text-bhon-navy">Preferências de contato</h2><p className="mt-1 text-xs leading-5 text-bhon-muted">A Sarah só prepara recuperação via WhatsApp quando este canal estiver autorizado.</p></div></div>{!value ? <p className="mt-4 flex items-center gap-2 text-xs text-bhon-muted"><Loader2 className="h-4 w-4 animate-spin" />Carregando preferências…</p> : <><div className="mt-4 grid gap-3 sm:grid-cols-3">{(['whatsapp', 'phone', 'email'] as const).map((field) => <label key={field} className="text-xs font-bold capitalize text-bhon-text">{field === 'whatsapp' ? 'WhatsApp' : field === 'phone' ? 'Telefone' : 'E-mail'}<select disabled={!canManage || saving} value={value[field]} onChange={(event) => update(field, event.target.value as ContactPreferenceStatus)} className="mt-1.5 min-h-10 w-full rounded-xl border border-bhon-border bg-white px-3 text-sm font-normal text-bhon-navy focus-visible:ring-2 focus-visible:ring-bhon-teal disabled:opacity-60">{Object.entries(labels).map(([status, label]) => <option key={status} value={status}>{label}</option>)}</select></label>)}</div>{canManage ? <button type="button" onClick={() => void save()} disabled={saving} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-xl bg-bhon-navy px-4 text-xs font-bold text-white hover:bg-bhon-navy-light focus-visible:ring-2 focus-visible:ring-bhon-teal disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'Salvando…' : 'Salvar preferências'}</button> : null}</>}{message ? <p aria-live="polite" className="mt-3 text-xs text-bhon-muted">{message}</p> : null}</section>;
}
