import { useState } from 'react';
import type { Protocol, ProtocolInput } from '../../lib/clinicConfiguration';

export function ProtocolEditor({ protocols, canManage, onSave }: { protocols: Protocol[]; canManage: boolean; onSave: (value: ProtocolInput, id?: string) => Promise<void> }) {
  const [draft, setDraft] = useState<ProtocolInput & { id?: string } | null>(null); const [error, setError] = useState('');
  const edit = (protocol?: Protocol) => setDraft(protocol ? { ...protocol } : { title: '', description: null, steps: [''], isActive: true });
  return <div className="space-y-4">{canManage && !draft && <button onClick={() => edit()} className="rounded-xl bg-bhon-navy px-4 py-2 text-sm font-bold text-white">Novo protocolo</button>}{draft && <form className="space-y-3 rounded-xl border p-4" onSubmit={async event => { event.preventDefault(); setError(''); try { if (draft.id) await onSave(draft, draft.id); else await onSave(draft); setDraft(null); } catch (e) { setError((e as Error).message); } }}>
    <label className="block text-xs font-bold">Título<input required minLength={2} maxLength={160} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} className="mt-1 block w-full rounded-lg border p-2" /></label>
    <label className="block text-xs font-bold">Descrição<textarea maxLength={4000} value={draft.description || ''} onChange={e => setDraft({ ...draft, description: e.target.value || null })} className="mt-1 block w-full rounded-lg border p-2" /></label>
    {draft.steps.map((step, index) => <div key={index} className="flex gap-2"><label className="flex-1 text-xs font-bold">Etapa {index + 1}<input aria-label={`Etapa ${index + 1}`} required maxLength={1000} value={step} onChange={e => setDraft({ ...draft, steps: draft.steps.map((value, at) => at === index ? e.target.value : value) })} className="mt-1 block w-full rounded-lg border p-2" /></label>{draft.steps.length > 1 && <button type="button" onClick={() => setDraft({ ...draft, steps: draft.steps.filter((_, at) => at !== index) })}>Remover</button>}</div>)}
    <button type="button" onClick={() => setDraft({ ...draft, steps: [...draft.steps, ''] })} className="rounded-lg border px-3 py-2 text-xs font-bold">Adicionar etapa</button>{error && <p role="alert">{error}</p>}<div><button className="rounded-xl bg-bhon-teal px-4 py-2 text-sm font-bold text-white">Salvar</button></div>
  </form>}{protocols.length === 0 && !draft ? <p className="text-sm text-bhon-muted">Nenhum protocolo cadastrado.</p> : protocols.map(protocol => <article key={protocol.id} className="rounded-xl border p-4"><div className="flex justify-between"><div><h3 className="font-bold text-bhon-navy">{protocol.title}</h3><p className="text-xs text-bhon-muted">{protocol.steps.length} etapas · {protocol.isActive ? 'Ativo' : 'Inativo'}</p></div>{canManage && <div className="flex gap-2"><button onClick={() => edit(protocol)}>Editar</button><button onClick={() => void onSave({ ...protocol, isActive: !protocol.isActive }, protocol.id)}>{protocol.isActive ? 'Desativar' : 'Reativar'}</button></div>}</div></article>)}</div>;
}
