const CLINIC_OPERATION_ROLES = ["OWNER", "ADMIN", "MANAGER", "DENTIST", "RECEPTIONIST"] as const;

export const PATIENT_WRITE_ROLES = CLINIC_OPERATION_ROLES;
export const APPOINTMENT_WRITE_ROLES = CLINIC_OPERATION_ROLES;
export const APPOINTMENT_STATUS_ROLES = CLINIC_OPERATION_ROLES;
export const CLINICAL_STAGE_WRITE_ROLES = ["OWNER", "ADMIN", "MANAGER", "DENTIST"] as const;
