import React, { useEffect, useMemo, useState } from 'react';
import { Boxes, ExternalLink, FileText, MessageCircle, PackagePlus, PlugZap, RefreshCw, Send } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { listFollowUps } from '../../lib/clinic';
import { configureIntegration, createDocument, createInventoryItem, listDocuments, listIntegrations, listInventory, moveInventory, type ClinicDocument, type IntegrationConnection, type InventoryItem } from '../../lib/operations';
import type { FollowUp } from '../../types';

const canManage = (role: string) => ['OWNER', 'ADMIN', 'MANAGER'].includes(role);
const PageHeader = ({ eyebrow, title, description, icon: Icon }: { eyebrow: string; title: string; description: string; icon: React.ElementType }) => (
  <header className="flex flex-col gap-4 rounded-3xl border border-white/[0.07] bg-[#14161A] p-6 sm:flex-row sm:items-end sm:justify-between sm:p-8">
    <div><p className="bhon-eyebrow">{eyebrow}</p><h1 className="mt-2 font-display text-3xl font-semibold text-white">{title}</h1><p className="mt-2 max-w-2xl text-sm text-bhon-muted">{description}</p></div>
    <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-bhon-teal/10 text-bhon-teal"><Icon className="h-5 w-5" aria-hidden="true" /></div>
  </header>
);
const Notice = ({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'error' }) => <div role={tone === 'error' ? 'alert' : 'status'} className={`rounded-2xl border px-4 py-3 text-sm ${tone === 'error' ? 'border-rose-400/20 bg-rose-400/10 text-rose-200' : 'border-white/[0.07] bg-white/[0.025] text-bhon-muted'}`}>{children}</div>;

export const WhatsAppPage: React.FC = () => {
  const [items, setItems] = useState<FollowUp[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); void listFollowUps({ status: 'PENDENTE', limit: 50 }, controller.signal).then((r) => setItems(r.data)).catch((e) => { if (e.name !== 'AbortError') setError(e.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  const contactable = useMemo(() => items.filter((item) => item.patientPhone), [items]);
  const link = (item: FollowUp) => `https://wa.me/${(item.patientPhone || '').replace(/\D/g, '')}?text=${encodeURIComponent(`Olá, ${item.patientName}. Aqui é da clínica. Entramos em contato sobre: ${item.reason}.`)}`;
  return <div className="mx-auto max-w-[1480px] space-y-6"><PageHeader eyebrow="Relacionamento" title="Central WhatsApp" description="Contatos clínicos pendentes, com abertura segura da conversa no WhatsApp." icon={MessageCircle} />
    {error ? <Notice tone="error">{error}</Notice> : null}<Notice>A BHON abre a conversa no WhatsApp. Histórico sincronizado e disparos automáticos só serão liberados após a conexão oficial do provedor.</Notice>
    <section className="bhon-panel overflow-hidden rounded-2xl"><div className="border-b border-bhon-border px-5 py-4"><h2 className="font-display text-xl">Fila de contatos</h2><p className="mt-1 text-xs text-bhon-muted">{loading ? 'Atualizando…' : `${contactable.length} contatos com telefone disponível`}</p></div>
      <div className="divide-y divide-bhon-border">{!loading && contactable.length === 0 ? <p className="p-8 text-center text-sm text-bhon-muted">Nenhum contato pendente com telefone cadastrado.</p> : contactable.map((item) => <div key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-white">{item.patientName}</p><p className="mt-1 text-xs text-bhon-muted">{item.reason} · {item.patientPhone}</p></div><a href={link(item)} target="_blank" rel="noreferrer" className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-bhon-teal px-4 text-sm font-bold text-[#07120F]"><Send className="h-4 w-4" /> Abrir conversa</a></div>)}</div>
    </section></div>;
};

export const InventoryPage: React.FC = () => {
  const { currentUser } = useAuth(); const [items, setItems] = useState<InventoryItem[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const reload = () => { setLoading(true); setError(''); void listInventory().then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(reload, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { await createInventoryItem({ name: String(form.get('name')), sku: String(form.get('sku') || ''), unit: String(form.get('unit') || 'un'), currentStock: Number(form.get('stock') || 0), minimumStock: Number(form.get('minimum') || 0) }); event.currentTarget.reset(); reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao cadastrar item.'); } finally { setSaving(false); } };
  const movement = async (item: InventoryItem, type: 'ENTRY' | 'EXIT') => { const raw = window.prompt(`Quantidade para ${type === 'ENTRY' ? 'entrada' : 'saída'} de ${item.name}:`); if (!raw) return; const quantity = Number(raw.replace(',', '.')); if (!(quantity > 0)) { setError('Informe uma quantidade válida.'); return; } try { await moveInventory(item.id, { type, quantity }); reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao movimentar estoque.'); } };
  return <div className="mx-auto max-w-[1480px] space-y-6"><PageHeader eyebrow="Suprimentos" title="Estoque clínico" description="Saldo real de materiais, mínimos operacionais e movimentações auditadas." icon={Boxes} />{error ? <Notice tone="error">{error}</Notice> : null}
    {canManage(currentUser.role) ? <form onSubmit={submit} className="bhon-panel grid gap-3 rounded-2xl p-5 sm:grid-cols-5"><input name="name" required minLength={2} placeholder="Material" className="rounded-xl border p-3 text-sm sm:col-span-2" /><input name="sku" placeholder="Código" className="rounded-xl border p-3 text-sm" /><input name="unit" placeholder="Unidade" defaultValue="un" className="rounded-xl border p-3 text-sm" /><div className="grid grid-cols-2 gap-2"><input name="stock" type="number" min="0" step="0.001" placeholder="Saldo" className="min-w-0 rounded-xl border p-3 text-sm" /><input name="minimum" type="number" min="0" step="0.001" placeholder="Mínimo" className="min-w-0 rounded-xl border p-3 text-sm" /></div><button disabled={saving} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-bhon-teal px-4 text-sm font-bold text-[#07120F] sm:col-span-5"><PackagePlus className="h-4 w-4" />{saving ? 'Salvando…' : 'Cadastrar material'}</button></form> : null}
    <section className="bhon-panel overflow-hidden rounded-2xl"><div className="overflow-x-auto"><table className="bhon-table"><thead><tr><th>Material</th><th>Código</th><th>Saldo</th><th>Mínimo</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{!loading && items.length === 0 ? <tr><td colSpan={6} className="py-10 text-center">Nenhum material cadastrado.</td></tr> : items.map((item) => { const low = Number(item.currentStock) <= Number(item.minimumStock); return <tr key={item.id}><td className="font-semibold">{item.name}</td><td>{item.sku || '—'}</td><td className="font-mono-data">{Number(item.currentStock)} {item.unit}</td><td className="font-mono-data">{Number(item.minimumStock)} {item.unit}</td><td><span className={low ? 'text-amber-300' : 'text-emerald-300'}>{low ? 'Repor' : 'Regular'}</span></td><td>{canManage(currentUser.role) ? <div className="flex gap-2"><button onClick={() => void movement(item, 'ENTRY')} className="rounded-lg bg-white/5 px-3 py-1.5">Entrada</button><button onClick={() => void movement(item, 'EXIT')} className="rounded-lg bg-white/5 px-3 py-1.5">Saída</button></div> : 'Consulta'}</td></tr>; })}</tbody></table></div></section></div>;
};

export const DocumentsPage: React.FC = () => {
  const { currentUser } = useAuth(); const [items, setItems] = useState<ClinicDocument[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const reload = () => void listDocuments().then(setItems).catch((e) => setError(e.message)); useEffect(reload, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { await createDocument({ title: String(form.get('title')), category: String(form.get('category')), fileName: String(form.get('fileName')), url: String(form.get('url')) }); event.currentTarget.reset(); reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao cadastrar documento.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-[1480px] space-y-6"><PageHeader eyebrow="Informação clínica" title="Documentos" description="Índice seguro de documentos e links externos da clínica, sem arquivos demonstrativos." icon={FileText} />{error ? <Notice tone="error">{error}</Notice> : null}
    {canManage(currentUser.role) ? <form onSubmit={submit} className="bhon-panel grid gap-3 rounded-2xl p-5 sm:grid-cols-2"><input name="title" required placeholder="Título" className="rounded-xl border p-3 text-sm" /><input name="category" required placeholder="Categoria" className="rounded-xl border p-3 text-sm" /><input name="fileName" required placeholder="Nome do arquivo" className="rounded-xl border p-3 text-sm" /><input name="url" required type="url" placeholder="https://…" className="rounded-xl border p-3 text-sm" /><button disabled={saving} className="min-h-11 rounded-xl bg-bhon-teal px-4 text-sm font-bold text-[#07120F] sm:col-span-2">{saving ? 'Salvando…' : 'Cadastrar documento'}</button></form> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.length === 0 ? <Notice>Nenhum documento cadastrado.</Notice> : items.map((item) => <a key={item.id} href={item.url} target="_blank" rel="noreferrer" className="bhon-panel flex items-start justify-between rounded-2xl p-5 transition-transform hover:-translate-y-0.5"><div><p className="text-xs font-bold uppercase tracking-wider text-bhon-teal">{item.category}</p><h2 className="mt-2 font-semibold text-white">{item.title}</h2><p className="mt-1 text-xs text-bhon-muted">{item.fileName}</p></div><ExternalLink className="h-4 w-4 text-bhon-muted" /></a>)}</div></div>;
};

export const IntegrationsPage: React.FC = () => {
  const { currentUser } = useAuth(); const [items, setItems] = useState<IntegrationConnection[]>([]); const [error, setError] = useState(''); const reload = () => void listIntegrations().then(setItems).catch((e) => setError(e.message)); useEffect(reload, []);
  const configure = async (provider: IntegrationConnection['provider']) => { const label = window.prompt('Identificação da conta ou unidade:'); if (!label) return; try { await configureIntegration(provider, { displayName: label, accountLabel: label }); reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao salvar integração.'); } };
  const names = { WHATSAPP: 'WhatsApp Business', GOOGLE_CALENDAR: 'Google Agenda', NFE: 'Emissão fiscal' };
  return <div className="mx-auto max-w-[1480px] space-y-6"><PageHeader eyebrow="Ecossistema" title="Integrações" description="Conexões da clínica com status explícito; nenhuma integração é marcada como ativa sem validação." icon={PlugZap} />{error ? <Notice tone="error">{error}</Notice> : null}<div className="grid gap-4 lg:grid-cols-3">{items.map((item) => <section key={item.provider} className="bhon-panel rounded-2xl p-5"><div className="flex items-center justify-between"><PlugZap className="h-5 w-5 text-bhon-teal" /><span className="rounded-full bg-white/5 px-3 py-1 text-[10px] font-bold uppercase text-bhon-muted">{item.status === 'NOT_CONFIGURED' ? 'Não configurada' : item.status === 'PENDING' ? 'Validação pendente' : item.status}</span></div><h2 className="mt-6 font-display text-xl text-white">{names[item.provider]}</h2><p className="mt-2 text-xs text-bhon-muted">{item.displayName || 'Nenhuma conta vinculada.'}</p>{canManage(currentUser.role) ? <button onClick={() => void configure(item.provider)} className="mt-6 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-white/10 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4" /> Configurar</button> : null}</section>)}</div></div>;
};
