import React, { useEffect, useState } from 'react';
import { LifeBuoy, Send } from 'lucide-react';
import { createSupportTicket, listSupportTickets, type ClinicTicket } from '../../lib/support';

export const SupportPage: React.FC = () => {
  const [tickets, setTickets] = useState<ClinicTicket[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => void listSupportTickets().then(setTickets).catch((e) => setError(e instanceof Error ? e.message : 'Não foi possível carregar os chamados.'));
  useEffect(load, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { await createSupportTicket({ title: String(form.get('title')), description: String(form.get('description')), priority: String(form.get('priority')) as ClinicTicket['priority'] }); event.currentTarget.reset(); load(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível abrir o chamado.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-5xl space-y-6"><header className="rounded-3xl border border-bhon-border bg-white p-6"><div className="flex items-center gap-3"><LifeBuoy className="h-5 w-5 text-bhon-teal" /><div><p className="text-xs font-semibold text-bhon-teal-dark">Suporte BHON</p><h1 className="text-2xl font-semibold text-bhon-text">Precisa de ajuda?</h1><p className="mt-1 text-sm text-bhon-muted">Abra um chamado. Quando concluirmos, você receberá um aviso na clínica.</p></div></div></header>{error ? <p role="alert" className="rounded border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900">{error}</p> : null}<form onSubmit={submit} className="grid gap-3 rounded-2xl border border-bhon-border bg-white p-5"><input required name="title" minLength={5} placeholder="Assunto do chamado" className="rounded-xl border border-bhon-border p-3 text-sm" /><textarea required name="description" minLength={10} rows={4} placeholder="Descreva o que aconteceu e o que você esperava." className="rounded-xl border border-bhon-border p-3 text-sm" /><select name="priority" className="rounded-xl border border-bhon-border p-3 text-sm"><option value="MEDIUM">Prioridade normal</option><option value="HIGH">Impacta a operação</option><option value="URGENT">Operação parada</option></select><button disabled={saving} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-bhon-teal px-4 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4" />{saving ? 'Enviando…' : 'Enviar chamado'}</button></form><section className="overflow-hidden rounded-2xl border border-bhon-border bg-white"><div className="border-b border-bhon-border p-4"><h2 className="font-semibold text-bhon-text">Seus chamados</h2></div>{tickets.length ? <div className="divide-y divide-bhon-border">{tickets.map((ticket) => <div key={ticket.id} className="p-4"><div className="flex justify-between gap-3"><strong className="text-sm text-bhon-text">{ticket.title}</strong><span className="text-xs text-bhon-teal-dark">{ticket.status}</span></div><p className="mt-1 text-xs text-bhon-muted">{ticket.description}</p></div>)}</div> : <p className="p-6 text-sm text-bhon-muted">Nenhum chamado aberto.</p>}</section></div>;
};
