import React from 'react';
import { PublicShell } from '../../components/public/PublicShell';
const terms = [
['1. Sobre a BHON', 'A BHON oferece ferramentas para organizar agenda, pacientes, equipe, orçamentos e acompanhamentos de clínicas. O serviço apoia a gestão: decisões clínicas, diagnósticos e condutas continuam sendo responsabilidade dos profissionais habilitados.'],
['2. Cadastro e acesso', 'O responsável pelo cadastro deve estar autorizado a representar a clínica, fornecer informações corretas e proteger suas credenciais. A clínica administra os acessos da equipe e deve comunicar imediatamente qualquer suspeita de uso indevido.'],
['3. Teste e assinatura', 'O teste dura 14 dias, conforme a data apresentada no checkout. O plano mensal custa R$ 290 por mês. O plano anual custa R$ 2.900 por ano, cobrado pelo período completo. O cartão é informado no ambiente da Stripe. Caso não haja cancelamento, a primeira cobrança ocorre após o teste e a assinatura renova no ciclo escolhido. Confira as datas e os valores antes de confirmar.'],
['4. Cancelamento e atendimento', 'Para solicitar cancelamento ou esclarecer uma cobrança, escreva para bhonsuport@gmail.com com o e-mail de cadastro da clínica. Solicite o cancelamento antes do fim do teste para evitar a primeira cobrança. O cancelamento interrompe renovações futuras; pedidos de reembolso serão analisados conforme a legislação aplicável e as condições da contratação.'],
['5. Uso responsável', 'Não utilize a plataforma para acesso não autorizado, envio de spam, fraude ou tratamento ilícito de dados. A clínica responde pela legitimidade das informações que insere e pela autorização ou outra base legal adequada para o contato com pacientes. O uso que ameace a segurança do serviço poderá ser restringido, com comunicação ao responsável quando cabível.'],
['6. Recursos e integrações', 'A disponibilidade de integrações depende de configuração e dos serviços de terceiros envolvidos. Não há garantia de aumento de receita, comparecimento ou recuperação de orçamento. Atualizações e manutenções podem afetar temporariamente o acesso; ocorrências podem ser reportadas ao suporte.'],
['7. Dados e encerramento', 'As práticas de tratamento estão descritas na Política de Privacidade. Antes de encerrar a contratação, a clínica deve solicitar orientações para recuperar seus dados e cumprir suas próprias obrigações de guarda. Pedidos de exclusão serão avaliados considerando obrigações legais e direitos de terceiros.'],
['8. Atualizações destes termos', 'Mudanças relevantes nas condições de contratação devem ser comunicadas ao responsável. As condições comerciais confirmadas no checkout devem ser consultadas junto destes termos. Dúvidas podem ser encaminhadas ao canal de suporte indicado nesta página.'],
];
const privacy = [
['1. A quem se aplica', 'Esta política descreve o tratamento de dados no site e na plataforma BHON. Para cadastro, cobrança e suporte da assinatura, a BHON decide as finalidades do tratamento. No uso dos registros de pacientes pela clínica, a clínica decide as finalidades e a BHON trata os dados conforme a prestação do serviço e as instruções aplicáveis.'],
['2. Quais informações são utilizadas', 'O cadastro pode incluir nome e contato do responsável, nome da clínica, e-mail, telefone e usuário de acesso. A operação pode incluir cadastros de pacientes, agenda, informações registradas pela equipe e orçamentos. Alguns registros podem conter dados de saúde, que exigem cuidado adicional. Registros técnicos de acesso e solicitações de suporte também podem ser tratados.'],
['3. Para que os dados são utilizados', 'As informações permitem criar e proteger os acessos, executar as funções contratadas, organizar a operação e responder solicitações. O cadastro e a cobrança são tratados para a contratação e execução do serviço e cumprimento de obrigações aplicáveis. O tratamento de dados de saúde deve observar a base legal adequada definida pela clínica, conforme sua atuação.'],
['4. Prestadores e pagamentos', 'A operação utiliza fornecedores de infraestrutura e banco de dados, como Vercel e Supabase. O checkout de pagamento é processado pela Stripe. O formulário da BHON não recebe o número completo do cartão. O acesso de prestadores deve estar relacionado à prestação do serviço; fornecedores podem processar dados em outros países, sujeitos às salvaguardas aplicáveis.'],
['5. Cookies e armazenamento local', 'Cookies de sessão sustentam o login, e preferências locais podem guardar escolhas de interface, como o tema. Esta versão do site público não instala ferramentas de publicidade ou análise de audiência. Se ferramentas opcionais forem adicionadas, suas finalidades e controles devem ser informados antes da ativação, quando exigido.'],
['6. Proteção e conservação', 'O sistema utiliza autenticação e permissões de acesso. Nenhum serviço elimina integralmente riscos de segurança. Os dados são conservados conforme a necessidade do serviço e as obrigações legais aplicáveis. A clínica deve observar seus prazos de guarda e solicitar orientação sobre exportação e encerramento; cópias de segurança podem seguir ciclos próprios de retenção.'],
['7. Seus direitos', 'Você pode solicitar informações sobre o tratamento, acesso, correção e, quando aplicável, exclusão ou outros direitos previstos na LGPD. Para registros de atendimento, procure primeiro a clínica responsável. Para dados da assinatura e suporte, escreva à BHON. Podemos pedir informações proporcionais para confirmar sua identidade e proteger os dados.'],
['8. Contato e atualizações', 'Envie dúvidas ou solicitações de privacidade para bhonsuport@gmail.com. Evite incluir diagnósticos, documentos clínicos ou outros dados sensíveis no primeiro contato. Esta política poderá ser atualizada para refletir mudanças no serviço, com indicação da data da versão.'],
];
export function LegalPage({ kind }: { kind: 'terms' | 'privacy' }) {
  return <PublicShell><div className="public-container public-legal"><a className="public-text-link" href="/">← Voltar ao site</a><p className="public-kicker">TRANSPARÊNCIA BHON</p><h1>{kind === 'terms' ? 'Termos de Uso' : 'Política de Privacidade'}</h1><p>Versão de 24 de setembro de 2026</p><p className="public-legal-notice"><strong>Documento em versão inicial.</strong> Este conteúdo passará por revisão jurídica antes do lançamento comercial definitivo.</p><article>{(kind === 'terms' ? terms : privacy).map(([title,text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}{kind === 'privacy' && <p className="public-legal-source">Saiba mais sobre seus direitos na <a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados/direito-dos-titulares" target="_blank" rel="noreferrer">orientação da ANPD</a>.</p>}</article></div></PublicShell>;
}
